volumes:
  qdrant_data:
  postgresql_data:

services:
  nss-qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: nss-qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage
  nss-pgsql:
    image: daxnet/nss-pgsql:latest
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    restart: always
    container_name: nss-pgsql
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nw_smart_store
    volumes:
      - postgresql_data:/var/lib/postgresql/data

configs:
  qdrant_config:
    content: |
      log_level: INFO